import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/styles/FieldInputs.css";
import "@/styles/BackendCustomChart.css";
import "@/styles/StepOfBackend.css";
import "@/styles/Sidebar.css";
import "react-toastify/dist/ReactToastify.css";
// import "@/Components/ToolsComponents/TechnologyBox/TechnologyBox.css";
// import "@/Components/ToolsComponents/FrameworkBox/FrameworkBox.css";
import { Providers } from "./components/shared/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TenGen",
  description: "Generated by TenGen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
